{% set name = "fastapi-pagination" %}
{% set version = "0.12.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastapi_pagination-{{ version }}.tar.gz
  sha256: b6f1978a341ed5aa534b04994619eef36377220c7ae11e933589cbfea9ae1c1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - pydantic >=1.9.1
    - fastapi >=0.93.0
  run_constrained:
    - SQLAlchemy >=1.3.20
    - databases >=0.6.0
    - orm >=0.3.1
    - tortoise-orm >=0.16.18,<0.20.0
    - asyncpg >=0.24.0
    - ormar >=0.11.2
    - django <5.0.0
    - piccolo >=0.89,<0.120
    - motor >=2.5.1,<4.0.0
    - mongoengine >=0.23.1,<0.28.0
    - sqlmodel >=0.0.8,<0.0.9
    - pony >=0.7.16,<0.8.0
    - beanie >=1.11.9,<2.0.0
    - sqlakeyset >=2.0.1680321678,<3.0.0
    - scylla-driver >=3.25.6,<4.0.0
    - bunnet >=1.1.0,<2.0.0

test:
  imports:
    - fastapi_pagination
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uriyyo/fastapi-pagination
  summary: FastAPI pagination
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sumanth-manchala
