{% set name = "fastapi-pagination" %}
{% set version = "0.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastapi_pagination-{{ version }}.tar.gz
  sha256: 5e76f129aef706601b86114428ca3ff68715bfa3929bf4df8c7ed27561d7f661

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0
    - pydantic >=1.9.1
    - fastapi >=0.93.0
  run_constrained:
    - SQLAlchemy >=1.3.20
    - databases >=0.6.0
    - orm >=0.3.1
    - tortoise-orm >=0.22.0
    - asyncpg >=0.24.0
    - odmantic>=1.0.2,<2
    - django <6.0.0
    - piccolo >=0.89,<1.25
    - motor>=3.6.0,<4.0.0
    - mongoengine >=0.23.1,<0.30.0
    - sqlmodel >=0.0.22
    - pony >=0.7.16,<0.8.0
    - beanie >=1.25.0
    - sqlakeyset >=2.0.1680321678,<3.0.0
    - scylla-driver >=3.25.6,<4
    - bunnet >=1.1.0,<2.0.0
    - elasticsearch-dsl>=8.13.0,<9
    - google-cloud-firestore>=2.19.0,<3

test:
  imports:
    - fastapi_pagination
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/uriyyo/fastapi-pagination
  summary: FastAPI pagination
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sumanth-manchala
